# Generated by Django 5.0.4 on 2024-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_courses_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='core.courses'),
        ),
    ]
